/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const UserCreation = t.iface(["Partial"], {
  "minecraft": "string",
  "displayname": "string",
  "hasBoundMinecraftID": "boolean",
  "latestLoginActionAt": "number",
  "regType": "UserRegType",
  "perm": "UserPerm",
});

export const IUser = t.iface([], {
  "id": "string",
  "displayname": "string",
  "minecraft": "string",
  "uuid": "string",
  "isOnline": "boolean",
  "hasBoundMinecraftID": "boolean",
  "latestLoginActionAt": "number",
  "regType": "UserRegType",
  "perm": "UserPerm",
});

export const CommonResponse = t.iface([], {
  "status": "RespStatus",
  "msg": "string",
  "data": "any",
});

export const OasisUserObject = t.iface([], {
  "uid": "number",
  "username": "string",
  "userslug": "string",
  "picture": "string",
  "status": "string",
  "postcount": "number",
  "reputation": "number",
  "email:confirmed": "number",
  "lastonline": "number",
  "flags": "null",
  "banned": "boolean",
  "banned:expire": "number",
  "joindate": "number",
  "fullname": "string",
  "displayname": "string",
  "icon:text": "string",
  "icon:bgColor": "string",
  "joindateISO": "Date",
  "lastonlineISO": "Date",
  "banned_until": "number",
  "banned_until_readable": "string",
});

export const NodeBBResponse = t.iface([], {
  "response": "OasisUserObject",
  "status": t.iface([], {
    "code": "string",
    "message": "string",
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  UserCreation,
  IUser,
  CommonResponse,
  OasisUserObject,
  NodeBBResponse,
};
export default exportedTypeSuite;
